### ISSUE TITLE
error processing mouse click

### ISSUE THREAD

**Issue by gyje** [AM429/anki2sm#11]
error processing mouse click item #1:document.createElement("section"),未指明的错误

**Comment by ghost** [comment]
Ah yeah that happens because section elements are not really supported by SM' IE renderer, if styling is not important you can let go of it, also some images may not render if you choose to embed them into the html

**Comment by gyje** [comment]
> Ah yeah that happens because section elements are not really supported by SM' IE renderer, if styling is not important you can let go of it, also some images may not render if you choose to embed them into the html

Thank you very much, the actual situation is like this, if I choose to embed the picture in html, the picture always shows the first one, and if you use the picture component, it can be displayed normally, but the default is to stretch the picture, which needs to be modified manually, can you add an option when converting, do not let the picture stretch.

**Comment by ghost** [comment]
I'll look into it but I think the culprit is SM, could you check the original image in the image path and let me know if it is stretched there?
