### ISSUE TITLE
Option to Convert Without Frame

### ISSUE THREAD

**Issue by rajlego** [AM429/anki2sm#3]
Converting from Anki to SM with frame makes it possible to render in SM exactly as shown in Anki; the downside is that you can longer apply template font styling to cards. Being able to convert without frame would be useful for cards that don't need to look exactly as they do in Anki.

**Comment by ghost** [comment]
Done! Added it on a per deck basis as of [commit](https://github.com/AM429/anki2sm/commit/42161b2170f0943186e88eb656158dcf903d999e)

**Comment by rajlego** [comment]
![image](https://user-images.githubusercontent.com/5921902/98458619-b340ce80-21b8-11eb-901e-6fd5f798eadb.png)
I'm getting an error when I try to convert this with no IE frame.
This is the deck I tried to convert (cut down):
[voracious cards.zip](https://github.com/AM429/anki2sm/files/5505912/voracious.cards.zip)

**Comment by ghost** [comment]
hmm so it's not an IE issue per se
![image](https://user-images.githubusercontent.com/58094765/98486310-46175280-2225-11eb-8c2a-4e28e611c4ab.png)
but i have seen this pop up maaaany times with people setting up the script and i have no clue why but i guess it is time to find out why.

**Comment by ghost** [comment]
Hopefully it should work now, also beware that not lifting IE restrictions is not going to make the images render within the html

**Comment by rajlego** [comment]
![image](https://user-images.githubusercontent.com/5921902/98501580-a6ce7b80-2275-11eb-920d-71098baaf10a.png)
It looks like IE frame isn't rendering for answer (as expected) but for some reason is still rendering under question.

**Comment by ghost** [comment]
if you mean the square border then that is a section element created by the script to contain the question/answer's contents and labels the section as `.card` class in cases there is some styling involved. Both the question and the answer field share the same code 
```
				if ALLOW_IE_COMPAT:
					a = insertHtmlAt(a, liftIERestriction, 'head', 0)
```
if you would rather have the section element removed then i could do that

**Comment by rajlego** [comment]
I am not 100% sure I understand you but my expectation was that when I did the "no IE frame" option there'd be no IE frame for both question + answer while it looks like it's remaining for the question but no the answer when disabled

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/58094765/98509840-a54b8600-226a-11eb-891f-990a6298fc25.png)

**Comment by rajlego** [comment]
I just found that that's a problem, I tried to change style on answer but it looks like the script part makes it not work unless I click and go to editing mode. Yeah, for IE frame free mode, it would be better to get rid of that so that supermemo styling applies fine.
```
<HTML><HEAD>
<SCRIPT>document.createElement("section");</SCRIPT>
<section class=card style="FONT-SIZE: 30px; HEIGHT: 100%; FONT-FAMILY: Noto Sans CJK JP Regular; WIDTH: 100%; COLOR: black; TEXT-ALIGN: center; MARGIN: 0px"></HEAD>
<BODY><FONT size=6>
<HR id=answer>
&#38738;&#31354;&#12398;&#20013;&#12395;&#28014;&#12363;&#12435;&#12391;&#12427;&#12415;&#12383;&#12356;&#12384;<BR><BR><BR><BR><RUBY><RB>&#38738;&#31354;</RB><RT>&#12354;&#12362;&#12382;&#12425;</RT></RUBY>&#12398;<RUBY><RB>&#20013;</RB><RT>&#12394;&#12363;</RT></RUBY>&#12395;<RUBY><RB>&#28014;</RB><RT>&#12358;</RT></RUBY>&#12363;&#12435;&#12391;&#12427;&#12415;&#12383;&#12356;&#12384;22:19/ 24:32&#38738;&#31354;&#12398;&#20013;&#12395;&#28014;&#12363;&#12435;&#12391;&#12427;&#12415;&#12383;&#12356;&#12384;&#8617;Subtitle Mode: Toggle HelpYahoo! goo &#33521;&#36766;&#37070; Jisho&#28014;&#12363;&#12406;JMdict (English)to float; to be suspended to rise to surface to come to mind; to have inspirati</FONT></section></BODY></HTML>
```

**Comment by ghost** [comment]
hopefully should work
