### ISSUE TITLE
anki2sm attempts to convert files that aren't cards

### ISSUE THREAD

**Issue by rajlego** [AM429/anki2sm#8]
![image](https://user-images.githubusercontent.com/5921902/100566623-de2ac800-3309-11eb-84bb-fc940a1e1700.png)
the log there ends up leading to this error:
![image](https://user-images.githubusercontent.com/5921902/100566646-ebe04d80-3309-11eb-88ed-2682971fa015.png)

which isn't a huge problem but filtering out non .apkg/colpkg and other anki formats from attempted conversion could be minorly useful

**Comment by ghost** [comment]
i think this should be solved now, do let me know if it hasnot
